# Generated by Django 5.1.5 on 2026-02-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_card_image_url_service_slug_servicedetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('design', 'Design'), ('cloud', 'Cloud'), ('devops', 'DevOps'), ('qa', 'QA'), ('game', 'Game')], default='mobile', max_length=40),
        ),
    ]
