# Generated by Django 5.1.5 on 2026-02-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/cards/'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/meta/'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='rich_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ServiceCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/carousel/')),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='core.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
