# Generated by Django 5.1.5 on 2026-02-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_card_image_servicedetail_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='scrum_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='section_type',
            field=models.CharField(choices=[('cards', 'Cards'), ('bullets', 'Bullets'), ('accordion', 'Accordion'), ('gallery', 'Gallery'), ('carousel', 'Carousel'), ('text', 'Text'), ('rich', 'Rich Text')], max_length=20),
        ),
    ]
